-- TABLE
DROP 
  TABLE IF EXISTS `area`;
CREATE TABLE IF NOT EXISTS `area` (
  -- COLUMNS,
  `id` INT NOT NULL AUTO_INCREMENT, 
  `name` VARCHAR(64) NOT NULL, 
  -- `address` VARCHAR(256) NOT NULL, 
  `latitude` DOUBLE, 
  `longitude` DOUBLE, 
  `code_area` VARCHAR(64),
  `notes` VARCHAR(256) DEFAULT '', 
  `status` TINYINT DEFAULT '1', 
  `flag` TINYINT DEFAULT '0', 
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
  -- INDEX
  PRIMARY KEY (`id`),
  UNIQUE (`code_area`)
   -- FOR FOREIGN KEY
  -- KEY `SELF_COLUMN_ID` (`SELF_COLUMN_ID`)
  -- CONSTRAINT `PUT_FK_ID` FOREIGN KEY (`SELF_COLUMN_ID`) REFERENCES `EXTERNAL_COLUMN` (`id`) ON DELETE CASCADE
  ) ENGINE = INNODB;
